server:
  port: 8080

spring:
  application:
    name: task-ai-backend
  profiles:
    active: dev

jackson:
  time-zone: Asia/Shanghai
  date-format: yyyy-MM-dd HH:mm:ss
  serialization:
    write-dates-as-timestamps: false
